nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: []
            allow_methods: []
            allow_headers: []
            max_age: 0