services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - APP_ENV=prod
      - DATABASE_URL=pgsql://user:password@db:5432/task_manager
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/%2f

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672" # Management UI

volumes:
  db_data: