api:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api

### User auth
login:
    path: /api/login

token_refresh:
    path: /api/token/refresh

#############################